# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107zNhBQKKGYSdkb_7TI1yPZdf-Dn-voL
"""

import os
import json
import pandas as pd
import gspread
from google.oauth2.service_account import Credentials
from transformers import pipeline
# Purono line: from serpapi import GoogleSearch (Eta kete din)
# Noutun line:
from serpapi.google_search import GoogleSearch
# ১. GitHub Secrets theke credentials neya
SERPAPI_KEY = os.getenv("SERPAPI_KEY")
GOOGLE_JSON = os.getenv("GOOGLE_CREDENTIALS")

# ২. Google Sheets Connect kora
scopes = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
creds_dict = json.loads(GOOGLE_JSON)
creds = Credentials.from_service_account_info(creds_dict, scopes=scopes)
gc = gspread.authorize(creds)

# ৩. AI Model Load kora
sentiment_analyzer = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")

def run_update():
    sh = gc.open("SeraDish_DB").sheet1
    df = pd.DataFrame(sh.get_all_records())

    final_scores = []
    for _, row in df.iterrows():
        params = {
            "engine": "google_maps_reviews",
            "place_id": row['Place ID'],
            "api_key": SERPAPI_KEY
        }
        search = GoogleSearch(params)
        reviews = search.get_dict().get("reviews", [])

        valid_scores = []
        tags = str(row['Category Tags']).split(',')
        for r in reviews:
            text = r.get("snippet", "")
            if text and any(tag.strip().lower() in text.lower() for tag in tags):
                res = sentiment_analyzer(text[:512])[0]
                valid_scores.append(int(res['label'].split()[0]))

        avg = sum(valid_scores) / len(valid_scores) if valid_scores else 0
        final_scores.append(round(avg, 2))

    df['Weekly Sentiment Score'] = final_scores
    sh.clear()
    sh.update([df.columns.values.tolist()] + df.values.tolist())
    print("✅ Sheet Updated Successfully!")

if __name__ == "__main__":
    run_update()
